version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - backend/.env
    environment:
      - VITE_MAPTILER_API_KEY=${VITE_MAPTILER_API_KEY}
      - PORT=3000
